spring.application.name=test

# ===============================
# DATASOURCE (POSTGRESQL LOCAL)
# ===============================
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/micro_portfolio

spring.datasource.url=jdbc:postgresql://localhost:5432/test_dans
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Info Document API
# ===============================
springdoc.openapi.info.title=API User Event
springdoc.openapi.info.version=1.0.0
springdoc.openapi.info.description=Documentation API for User - Event
springdoc.swagger-ui.path=/documentation-api

# ===============================
# JWT
# ===============================
jwt.secret-key=5F2A7D8C1E9B3A6F4D8E2C7A9B1D3F6A5C8E7B9D2F4A6C1E8B3D7F9A2C5E1B6
jwt.expiration=86400000